services:
    homecleaner:
      build:
        context: .
      command: python app/homecleaner/main.py
      environment:
        - HOMEMAKER_API=http://
      volumes:
        - ./app:/app/homecleaner:z
        - ./tests:/app/tests:z
        - ./pyproject.toml:/app/pyproject.toml:z
        - ./poetry.lock:/app/poetry.lock:z
      depends_on:
        homemaker-mock:
          condition: service_started

    homemaker-mock:
      image: wiremock/wiremock:3.2.0
      ports:
        - "127.0.0.1:8080:8080"
      volumes:
        - ./homemaker-mock/:/home/wiremock/mappings/:z

