services:
    homecleaner:
      build:
        context: .
      command: python -m app.main
      environment:
        - HOMEMAKER_API=http://
      volumes:
        - ./app:/app/homecleaner:z
        - ./tests:/app/tests:z
        - ./pyproject.toml:/app/pyproject.toml:z
        - ./poetry.lock:/app/poetry.lock:z